apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 78.3.2
    includeCRDs: true
    releaseName: kube-prometheus-stack
    namespace: monitoring
    # valuesFile: values.yaml
