apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-dylanmtaylor-com-config
  namespace: dylanmtaylor
data:
  VIRTUAL_HOST: "blog.dylanmtaylor.com,blog.dylanmtaylor.local"
  REDIRECT_SCHEME: "https"
  REDIRECT_TARGET: "dylanmtaylor.com"
  REDIRECT_PATH: "/blog"
