apiVersion: v1
kind: ConfigMap
metadata:
  name: www-dylanmtaylor-com-config
  namespace: dylanmtaylor
data:
  GIT_NAME: "Dylan M. Taylor"
  GIT_EMAIL: "dylan@dylanmtaylor.com"
  VIRTUAL_HOST: "www.dylanmtaylor.com,www.dylanmtaylor.local,dylanmtaylor.com,dylanmtaylor.local,localhost"
