apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-dylanmtaylor-com
  namespace: dylanmtaylor
  labels:
    app: git-dylanmtaylor-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-dylanmtaylor-com
  template:
    metadata:
      labels:
        app: git-dylanmtaylor-com
    spec:
      containers:
      - name: web-redirect
        image: docker.io/ajoergensen/web-redirect:latest
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - configMapRef:
            name: git-dylanmtaylor-com-config
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
