apiVersion: v1
kind: ConfigMap
metadata:
  name: git-dylanmtaylor-com-config
  namespace: dylanmtaylor
data:
  VIRTUAL_HOST: "git.dylanmtaylor.com,git.dylanmtaylor.local"
  REDIRECT_SCHEME: "https"
  REDIRECT_TARGET: "gitlab.com"
  REDIRECT_PATH: "/dylanmtaylor"
