apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-credentials
  namespace: dylanmtaylor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: SecretStore
  target:
    name: r2-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: r2-credentials
