apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: r2-credentials
  namespace: dylanmtaylor
spec:
  provider: oci
  parameters:
    authType: instance
    secrets: |
      - name: r2-credentials
        vaultId: ${VAULT_OCID}
        secretId: ${SECRET_OCID}
