apiVersion: v1
kind: Secret
metadata:
  name: oci-credentials
  namespace: dylanmtaylor
type: Opaque
stringData:
  # OCI Configuration file
  config: |
    user=ocid1.user.oc1..aaaaaaaah34ysvpsg5yvyqzvdb2msicyrnj7mnh2yicsg374gbpu525mfv2q
    fingerprint=a1:ae:2a:45:bd:13:08:1e:18:a0:ba:b8:4b:5c:6a:6e
    key_file=/root/.oci/oci_api_key.pem
    tenancy=ocid1.tenancy.oc1..aaaaaaaapryt5njqmdf6nt5n4q7kj7cjgqbivfkcho6rxlh4prbn4wvlppaq
    region=us-ashburn-1
  # OCI API Private Key (PEM format)
  # Replace this with your actual private key content
  oci_api_key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    <YOUR_PRIVATE_KEY_CONTENT_HERE>
    -----END RSA PRIVATE KEY-----
