apiVersion: v1
kind: Secret
metadata:
  name: oci-credentials
  namespace: dylanmtaylor
type: Opaque
stringData:
  # OCI Configuration file
  config: |
    [DEFAULT]
    user=ocid1.user.oc1..aaaaaaaah34ysvpsg5yvyqzvdb2msicyrnj7mnh2yicsg374gbpu525mfv2q
    fingerprint=97:b1:0d:6f:3d:4a:51:00:05:e4:41:a1:20:41:a6:40
    key_file=/root/.oci/oci_api_key.pem
    tenancy=ocid1.tenancy.oc1..aaaaaaaapryt5njqmdf6nt5n4q7kj7cjgqbivfkcho6rxlh4prbn4wvlppaq
    region=us-ashburn-1
  # OCI API Private Key (PEM format)
  # Replace this with your actual private key content
  oci_api_key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    <YOUR_PRIVATE_KEY_CONTENT_HERE>
    -----END RSA PRIVATE KEY-----
