apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-builder
  namespace: dylanmtaylor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resume-builder
  namespace: dylanmtaylor
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resume-builder
  namespace: dylanmtaylor
subjects:
  - kind: ServiceAccount
    name: resume-builder
    namespace: dylanmtaylor
roleRef:
  kind: Role
  name: resume-builder
  apiGroup: rbac.authorization.k8s.io
