apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: oci-loadbalancer
  namespace: dylanmtaylor
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 4
      envoyService:
        type: LoadBalancer
        loadBalancerIP: "129.80.142.204"
        annotations:
          oci.oraclecloud.com/load-balancer-type: "lb"
          service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
