apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: cloudflare-headers
  namespace: dylanmtaylor
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: dylanmtaylor-gateway
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  headers:
    enableEnvoyHeaders: false
