apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oci-vault
  namespace: dylanmtaylor
spec:
  provider:
    oracle:
      vault: "ocid1.vault.oc1.iad.ejs73rohaacvy.abuwcljt64kksh3va6xt6conjtor6yeht66qswu7g325jyaqt2cvmwfso32q"
      region: us-ashburn-1
      principalType: InstancePrincipal
