apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: load-balancer-ip
  namespace: dylanmtaylor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: SecretStore
  target:
    name: load-balancer-ip
    creationPolicy: Owner
  data:
  - secretKey: ip
    remoteRef:
      key: load-balancer-public-ipv4
