apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oci-vault
  namespace: dylanmtaylor
spec:
  provider:
    oracle:
      vault: "dylanmtaylor"  # Vault name works here instead of OCID
      region: us-ashburn-1
      principalType: InstancePrincipal
